services:
  - type: web
    name: djgoldbot
    env: python
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BOT_TOKEN
        value: 7524328423:AAGbx7KMgXRzIr9gAmg9I4WznFRmWiXKuNQ
